### ISSUE TITLE
Core Balancing Algorithm Enhancements

### ISSUE THREAD

**Issue by sawyercade** [datarank/tempest#13]
ModelBalancer balances by recursively forking (up to cluster_concurrent_rebalance times) the cluster one move operation at a time, returning the first goal cluster whose balance is better than the starting cluster with cluster_concurrent_rebalance moves, or less if it worked itself into a state where no further moves were possible.

An improved algorithm would 

1. Only evaluate the balance after cluster_concurrent_rebalance moves have been performed.
2. Repeat this simulation process some configured number of times, returning the best of all simulated goal clusters, which are all better balanced than the current cluster. This simulation will take longer, but should drastically reduce the number of extraneous/unnecessary moves and thus reduce the time it takes for the cluster to stabilize.
3. Trim move operations from the goal cluster that do not improve balance.

**Comment by aewhite** [comment]
Tempest 2.x has a whole new modeling and evaluation system.
