### ISSUE TITLE
Allocate unassigned shards on rebalance

### ISSUE THREAD

**Issue by sawyercade** [datarank/tempest#14]
When the cluster has unassigned shards, rebalance returns immediately and assumes the caller has/will call allocateUnassigned(). This isn't a great assumption, though true in some cases. There's no harm in allocating unassigned shards through the rebalance function.

**Comment by aewhite** [comment]
The underlying contract with ES on when allocation decisions is made is outlined in the interface. Rebalance should *not* allocate shards.
