### ISSUE TITLE
Tempest with ElasticSearch 1.7.3

### ISSUE THREAD

**Issue by stachdude** [datarank/tempest#17]
Seems, that the plugin is not compatible with version 1.7.3, as I was unable to start the cluster with ```cluster.routing.allocation.type: com.datarank.tempest.allocator.LocalMinimumShardsAllocator``` enabled. 

Can you please verify ?

**Comment by kungdernulf** [comment]
@stachdude It is somewhat compatible.
I'm not involved in the tempest project but we started using the plugin at my company a few weeks ago and we're also running ES 1.7.3.

Our config:
cluster.routing.allocation.type: com.datarank.tempest.allocator.LocalMinimumShardsAllocator
cluster.routing.allocation.probabilistic.range_ratio: 1.2

However, we do have a problem with the plugin throwing exceptions ocassionally when trying to allocate shards. See #15 which as reported by us.

**Comment by aewhite** [comment]
This should be resolved in Tempest 2.0.2
