### ISSUE TITLE
Heterogeneous Cluster Balancing

### ISSUE THREAD

**Issue by sawyercade** [datarank/tempest#5]
Not all clusters will be homogeneous. If there exists a significant difference between the resources available to two or more prospective nodes, balancing based on the size of nodes is counterproductive and can lead to instability.

ModelBalancer should be extended to account for the capacity of nodes in the cluster. This can be achieved by using the fullness of a node (total_size_of_shards_on_node / node_capacity) instead of just the total size of the shards on a node when calculating the balance of a potential goal cluster state.

**Comment by aewhite** [comment]
This is handled in 2.x via node attributes
