### ISSUE TITLE
Add support for versions above ES 1.4.3

### ISSUE THREAD

**Issue by sawyercade** [datarank/tempest#8]
POM file currently specifies v1.4.3 of ES as a dependency. However, tempest should run just as well in any version above v1.4.3 as well. Modify POM to support higher versions or create multiple release versions to match multiple supported ES versions.

**Comment by cfeio** [comment]
What is the status of this? What versions of ES are supported?

**Comment by sawyercade** [comment]
Currently we've tested on 1.4.2 and 1.5.2. From what I've seen of 1.6.0, the interfaces utilized by tempest have only been added to, not modified, so I'd hazard a guess that 1.6.0 will work as well. I'll run some tests this weekend and put an updated list of supported versions in the README.

**Comment by sawyercade** [comment]
For anyone interested, I've tested up through 1.7.1 and everything is working as expected. So any version between 1.4.2 and 1.7.1 (inclusive) is supported.
